# CONF. DO ZSH
# Local: ~/.zshrc

# Caminho da instalação do Oh-My-ZSH
  export ZSH=$HOME/.oh-my-zsh
  export IM=$HOME/.darth-instaulous

# CONF. ESPECIFICAS DO ZSH
HISTSIZE=100000
DEFAULT_USER=$USER

# TEMA
# Download em: https://github.com/robbyrussell/oh-my-zsh/wiki/Themes)
ZSH_THEME="agnoster"

# PLUGINS
# Local: ~/.oh-my-zsh/plugins/

# Instalação
# ZSH Auto Suggestions (git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions)
plugins=(
  git
  zsh-autosuggestions
  colored-man-pages
  docker
  history
  lol
  pylint
  pyenv
  python
  systemd
  sudo
)



source $ZSH/oh-my-zsh.sh
source $IM/confs/shells/aliases.sh
# CONF. DE USUARIO

# CONF. Tilix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

# Adiciona no PATH
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Adiciona no PATH
if [ -d "$HOME/.darth-instaulous/exec" ] ; then
    PATH="$HOME/.darth-instaulous/exec:$PATH"
fi


# Aliases

#source <(kubectl completion zsh)
. /usr/local/bin/powerline/powerline/bindings/zsh/powerline.zsh
